"""Closed-form synthetic ocean fields for the Bay of Bengal.

Every field is an analytic function of (lon, lat, depth, t) -- no solver, the
whole dataset evaluates in seconds. The goal is not physical accuracy but
*recognisability*: an evaluator at an ocean-sciences ministry knows what the Bay
of Bengal looks like, and a demo over plausible structure reads completely
differently from a demo over noise.

The one genuinely load-bearing choice here is that u/v are derived as the curl
of a streamfunction, so the horizontal flow is non-divergent. Without that,
GPU-advected particles pile into sinks and the current layer looks broken.
"""

from __future__ import annotations

from contextlib import contextmanager

import numpy as np

EARTH_RADIUS = 6_371_000.0

# Scales the mesoscale (eddy) contribution. The climatology is generated by
# re-evaluating these same functions with it set to 0, so an anomaly is "versus
# climatology" in a defensible sense rather than "versus a smoothed copy of
# itself".
EDDY_SCALE = 1.0


@contextmanager
def no_eddies():
    """Temporarily switch off mesoscale features (used to build climatology)."""
    global EDDY_SCALE
    prev = EDDY_SCALE
    EDDY_SCALE = 0.0
    try:
        yield
    finally:
        EDDY_SCALE = prev


# --- time-varying mesoscale features ------------------------------------


def eddies(day: float) -> list[tuple[float, float, float, float]]:
    """Mesoscale eddies as (lon, lat, amplitude_degC, radius_deg).

    They translate westward at a few km/day, which is what gives the 4D
    timeline something worth watching.
    """
    drift = day * 0.045  # deg/day westward
    return [
        (89.6 - drift, 16.2, +2.1, 1.35),  # warm core
        (86.1 - drift * 0.8, 12.4, -1.7, 1.10),  # cold core
        (91.8 - drift * 0.6, 9.1, +1.4, 1.55),  # warm core
    ]


def _eddy_field(lon2: np.ndarray, lat2: np.ndarray, day: float) -> np.ndarray:
    """Surface-intensified eddy anomaly pattern, in degrees C."""
    out = np.zeros_like(lon2)
    for elon, elat, amp, rad in eddies(day):
        out += EDDY_SCALE * amp * np.exp(
            -(((lon2 - elon) / rad) ** 2 + ((lat2 - elat) / rad) ** 2)
        )
    return out


def mixed_layer_depth(lon2: np.ndarray, lat2: np.ndarray, day: float) -> np.ndarray:
    """MLD in metres: shallow and fresh in the north, deeper to the south."""
    base = 30.0 + 55.0 * (1.0 - (lat2 - lat2.min()) / max(np.ptp(lat2), 1e-9))
    seasonal = 12.0 * np.sin(2 * np.pi * (day / 365.0))
    wobble = 6.0 * np.sin(lon2 * 0.9 + day * 0.05)
    return np.clip(base + seasonal + wobble, 18.0, 110.0)


# --- temperature ---------------------------------------------------------


def temperature(
    lon2: np.ndarray, lat2: np.ndarray, depth: np.ndarray, day: float
) -> np.ndarray:
    """thetao (depth, lat, lon) in degrees C."""
    mld = mixed_layer_depth(lon2, lat2, day)

    # Warm, near-uniform surface layer with a north-south gradient.
    sst = 29.4 - 0.10 * (lat2 - lat2.min()) + 0.35 * np.sin(2 * np.pi * day / 365.0)
    sst = sst + _eddy_field(lon2, lat2, day)

    # Coastal upwelling along the western boundary cools the surface.
    west_frac = np.clip(1.0 - (lon2 - lon2.min()) / 2.6, 0.0, 1.0)
    sst = sst - 1.9 * west_frac * (0.6 + 0.4 * np.sin(day * 0.08))

    z = depth[:, None, None]
    mld3 = mld[None, :, :]
    sst3 = sst[None, :, :]

    # tanh thermocline below the mixed layer, decaying to ~4 C at 2000 m.
    deep = 3.8 - 1.6 * np.clip((z - 1500.0) / 2500.0, 0, 1)
    thermo_scale = 260.0
    frac = 0.5 * (1.0 + np.tanh((z - mld3 * 1.25) / thermo_scale))
    t = sst3 * (1.0 - frac) + deep * frac

    # Keep the mixed layer genuinely mixed.
    in_mld = z <= mld3
    t = np.where(in_mld, sst3, t)
    return t.astype(np.float32)


# --- salinity ------------------------------------------------------------


def salinity(
    lon2: np.ndarray, lat2: np.ndarray, depth: np.ndarray, day: float
) -> np.ndarray:
    """so (depth, lat, lon) in practical salinity units.

    The defining feature of the Bay of Bengal: a Ganges-Brahmaputra freshwater
    cap in the north, confined to the top few tens of metres, spreading
    south-west. It is what makes the salinity volume and isosurface interesting
    instead of a flat slab.
    """
    z = depth[:, None, None]

    lat_n = (lat2 - lat2.min()) / max(np.ptp(lat2), 1e-9)
    lon_n = (lon2 - lon2.min()) / max(np.ptp(lon2), 1e-9)

    # Plume strength: strongest at the northern head, advected south-west.
    plume = np.exp(-(((1.0 - lat_n) / 0.38) ** 2)) * np.exp(-(((lon_n - 0.45) / 0.55) ** 2))
    plume = plume * (0.75 + 0.25 * np.sin(2 * np.pi * (day / 365.0) + 1.1))

    surface = 34.8 - 3.9 * plume  # down to ~31 psu at the head
    deep = 34.95 + 0.25 * np.clip((z - 200.0) / 1800.0, 0, 1)

    # Halocline: the freshwater cap is shallow, ~40 m.
    cap = np.exp(-(z / 40.0) ** 2)
    s = deep * (1.0 - cap) + surface[None, :, :] * cap
    return s.astype(np.float32)


# --- currents, from a streamfunction -------------------------------------


def _streamfunction(lon2: np.ndarray, lat2: np.ndarray, day: float) -> np.ndarray:
    """psi in m^2/s. Amplitude tuned so surface speeds land near 0.2-1.2 m/s."""
    amp = 1.55e5

    lat_n = (lat2 - lat2.min()) / max(np.ptp(lat2), 1e-9)
    lon_n = (lon2 - lon2.min()) / max(np.ptp(lon2), 1e-9)

    # East India Coastal Current: a western boundary jet.
    jet = -amp * 1.25 * np.exp(-((lon_n / 0.16) ** 2)) * np.sin(np.pi * np.clip(lat_n, 0, 1))

    # Broad basin-scale circulation.
    gyre = amp * 0.45 * np.sin(np.pi * lon_n) * np.sin(np.pi * lat_n)

    # The same eddies that appear in the temperature field, so the two are
    # physically consistent with one another.
    eddy = np.zeros_like(lon2)
    for elon, elat, a, rad in eddies(day):
        eddy += EDDY_SCALE * amp * 0.85 * np.sign(a) * np.exp(
            -(((lon2 - elon) / rad) ** 2 + ((lat2 - elat) / rad) ** 2)
        )

    return jet + gyre + eddy


def currents(
    lon: np.ndarray, lat: np.ndarray, depth: np.ndarray, day: float
) -> tuple[np.ndarray, np.ndarray]:
    """Return (uo, vo), each (depth, lat, lon) in m/s.

    u = -(1/R) dpsi/dlat ,  v = (1/(R cos(lat))) dpsi/dlon

    Taking the curl of a streamfunction guarantees a non-divergent field, which
    is the property the particle advection layer depends on.
    """
    lon2, lat2 = np.meshgrid(lon, lat)
    psi = _streamfunction(lon2, lat2, day)

    dlat = np.deg2rad(np.gradient(lat))
    dlon = np.deg2rad(np.gradient(lon))

    dpsi_dlat = np.gradient(psi, axis=0) / dlat[:, None]
    dpsi_dlon = np.gradient(psi, axis=1) / dlon[None, :]

    coslat = np.cos(np.deg2rad(lat2))
    coslat = np.where(np.abs(coslat) < 1e-6, 1e-6, coslat)

    u_surf = -dpsi_dlat / EARTH_RADIUS
    v_surf = dpsi_dlon / (EARTH_RADIUS * coslat)

    # Surface-intensified, decaying with an e-folding scale of 300 m.
    decay = np.exp(-depth / 300.0)[:, None, None]
    u = (u_surf[None, :, :] * decay).astype(np.float32)
    v = (v_surf[None, :, :] * decay).astype(np.float32)
    return np.clip(u, -2.5, 2.5), np.clip(v, -2.5, 2.5)


# --- chlorophyll ---------------------------------------------------------


def chlorophyll(
    lon2: np.ndarray, lat2: np.ndarray, depth: np.ndarray, day: float
) -> np.ndarray:
    """chl (depth, lat, lon) in mg m-3, with a subsurface maximum."""
    z = depth[:, None, None]

    lon_n = (lon2 - lon2.min()) / max(np.ptp(lon2), 1e-9)
    lat_n = (lat2 - lat2.min()) / max(np.ptp(lat2), 1e-9)

    # Coastal and riverine enrichment, plus a western upwelling band.
    coastal = 2.6 * np.exp(-((lon_n / 0.14) ** 2)) + 1.8 * np.exp(-(((1 - lat_n) / 0.22) ** 2))
    open_ocean = 0.14 + 0.10 * np.sin(2 * np.pi * day / 365.0 + lon_n * 3.0)
    surface = coastal + open_ocean

    # Subsurface chlorophyll maximum around 50-70 m.
    scm_depth = 58.0 + 12.0 * np.sin(lon2 * 0.7 + day * 0.03)
    scm = np.exp(-(((z - scm_depth[None, :, :]) / 26.0) ** 2))
    decay = np.exp(-z / 95.0)

    chl = surface[None, :, :] * (0.55 * decay + 0.85 * scm)
    return np.clip(chl, 0.0, 10.0).astype(np.float32)
